#!/usr/bin/env bash
#
# Example: a daily brief generated by Claude and delivered over Telegram.
#
# Install with crontab -e:
#   30 6 * * * $HOME/claude-telegram/examples/morning-brief.sh
#
# Adapt the prompt to whatever you actually want to wake up to. The pattern is
# the point: run `claude -p` headless, pipe the result to tg-push, and make sure
# failures are visible.
set -euo pipefail

# cron runs with a minimal PATH and does NOT source your shell profile, so
# `claude` and `tg-push` will not be found unless you put them on PATH here.
# The same applies to systemd units. This is the single most common reason a
# job that works in your terminal does nothing at 06:30.
export PATH="$HOME/.local/bin:$HOME/.npm-global/bin:/usr/local/bin:/usr/bin:/bin"

LOG="$HOME/morning-brief.log"

PROMPT=$(cat <<'PROMPT_EOF'
Generate a concise morning brief for me. Under 2000 characters total.
Output the brief only — no preamble, no closing remarks. Markdown is fine.

Sections, in this order:

1. Weather — curl the forecast for your location, e.g.
   "https://api.open-meteo.com/v1/forecast?latitude=51.5&longitude=-0.1&current=temperature_2m,precipitation&daily=temperature_2m_min,temperature_2m_max,precipitation_probability_max&timezone=Europe/London&forecast_days=1"
   One line: temperature now, high/low, chance of rain.

2. Today — read ~/notes/today.md and summarise anything happening today.

3. Overdue — read ~/notes/todo.md and list anything past its date. Skip the
   section entirely if nothing is overdue.

Rules:
- If a fetch or a file read fails, say so in one honest line. Never invent
  data, and never pad a section to look complete.
- Put whatever changes what you DO today first. Nice-to-know goes last.
PROMPT_EOF
)

# --dangerously-skip-permissions is required for unattended runs: there is
# nobody at the keyboard to approve tool calls. Only do this for prompts you
# have read, on a machine you control.
if OUT=$(claude -p "$PROMPT" --dangerously-skip-permissions 2>>"$LOG"); then
    printf '%s' "$OUT" | tg-push --title "☀️ Morning brief"
else
    # Push the failure too. Otherwise a broken job is indistinguishable from a
    # quiet morning, and you find out weeks later.
    tg-push <<<"⚠️ morning brief failed — see $LOG"
    exit 1
fi
